config/routes.rb
Rails.application.routes.draw do
  resources :sizes

  get 'static_pages/home'

  get 'static_pages/help'

  resources :artcats

  resources :fonts

  resources :printjobs do
    collection do
      get 'update_shirts'
      get 'update_details'
      get 'mark_completed'
      get 'update_artworks'
      get 'update_art'
    end
  end

  resources :artworks do
    collection do
      get 'catalog'
      get 'update_catalog'
      
      
    end
    member do
      get 'reorder'
    end
  end

  resources :shirts do
    member do
      get :update_size
      get :update_color
  end
  end

  resources :colors

  resources :mods do
    member do
      
      get :delete_size
      
    end
  end

  resources :shapes

  get 'printjobs/new'

  get 'artworks/update_catalog', as: 'update_catalog'

  
  get '/artworks/:id/update_artcat', to: 'artworks#update_artcat', as: 'update_artcat'
  
  get '/artworks/:id/delete_artcat', to: 'artworks#delete_artcat', as: 'delete_artcat'
  
 

  get 'printjobs/new2', as: 'new'

get 'printjobs/update_mods', :as => 'update_mods'
get 'printjobs/update_colors_sizes', :as => 'update_colors_sizes'

root 'static_pages#home'

end

app/models/mod.rb
class Mod < ActiveRecord::Base

	belongs_to :shape
	has_many :printjob
	has_and_belongs_to_many :color, join_table: :mods_and_colors
	has_and_belongs_to_many :size, join_table: :mods_and_sizes

end

app/controllers/mods_controller.rb
class ModsController < ApplicationController
  before_action :set_mod, only: [:show, :edit, :update, :destroy]

  # GET /mods
  # GET /mods.json
  def index
    @mods = Mod.all
  end

  # GET /mods/1
  # GET /mods/1.json
  def show
   
    @colors = @mod.color
    @sizes = @mod.size
  end

  # GET /mods/new
  def new
    @mod = Mod.new
  end

  # GET /mods/1/edit
  def edit
  end

  # POST /mods
  # POST /mods.json
  def create
    #byebug
    @mod = Mod.new(mod_params)

    respond_to do |format|
      if @mod.save
        format.html { redirect_to @mod, notice: 'Mod was successfully created.' }
        format.json { render :show, status: :created, location: @mod }
      else
        format.html { render :new }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mods/1
  # PATCH/PUT /mods/1.json
  def update
    @colors = @mod.color
    @sizes = @mod.size
    respond_to do |format|
      if @mod.update(mod_params)
        format.html { redirect_to @mod, notice: 'Mod was successfully updated.' }
        format.json { render :show, status: :ok, location: @mod }
      else
        format.html { render :edit }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  def add_size
    @colors = @mod.color
    @sizes = @mod.size
    @size = Size.find(params[:size])
    @mod.size << @size
    respond_to do |format|
      if @mod.update(mod_params)
        format.html { redirect_to @mod, notice: 'Size was successfully added.' }
        format.json { render :show, status: :ok, location: @mod }
      else
        format.html { render :edit }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete_size
   @mod = Mod.find(params[:id])
    @size = Size.find(params[:size])
    @mod.size.delete(@size)
    respond_to do |format|
      if true
        format.html { redirect_to @mod, notice: 'Size was successfully deleted.' }
        format.json { render :show, status: :ok, location: @mod }
      else
        format.html { render :edit }
        format.json { render json: @mod.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mods/1
  # DELETE /mods/1.json
  def destroy
    @mod.destroy
    respond_to do |format|
      format.html { redirect_to mods_url, notice: 'Mod was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mod
      @mod = Mod.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mod_params
      #params.require(:mod).permit(:shape_id, :description, :size)
    end
end

app/helpers/mods_helper.rb
module ModsHelper
end

app/views/mods/_form.html.erb
<%= form_for(@mod) do |f| %>
<% if @mod.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(@mod.errors.count, "error") %>prohibited this mod from being saved:</h2>
  <ul>
    <% @mod.errors.full_messages.each do |message| %>
    <li>
      <%= message %></li>
    <% end %></ul>
</div>
<% end %>
<div class="field">
  <%= f.label :shape_id %>
  <br>
  <%= f.number_field :shape_id %></div>
<div class="field">
  <%= f.label :description %>
  <br>
  <%= f.text_field :description %></div>
<div class="actions">
  <%= f.submit %></div>

  <% end %>

app/views/mods/_mod.html.erb
<option value="<%= mod.id %>"><%= mod.description %></option>

app/views/mods/edit.html.erb
<h1>Modifica Modello</h1>

<%= render 'form' %>


<%= link_to 'Torna a Elenco Modelli', mods_path , :class=>"button large"%>

app/views/mods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Elenco Modelli</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Descrizione</th>
      <th>Taglie</th>
      <th>Colori</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mods.each do |mod| %>
      <tr >
        <td><%= if mod.shape then mod.shape.description else "Tipo inesistente" end %></td>
        <td><%= mod.description %></td>
        <td><%= mod.size.map{|s| s.description}.join(", ") %></td>
        <td><%= mod.color.map{|c| c.description}.join(", ") %></td>
        <td><%= link_to 'Modifica', edit_mod_path(mod) %></td>
        <td><%= link_to 'Colori/Taglie', mod %></td>
        <td><%= link_to 'Elimina', mod, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Aggiungi Nuovo', new_mod_path, :class=>"button large" %>  <%= link_to 'Torna al pannello di controllo', root_path , :class=>"button large" %>

app/views/mods/new.html.erb
<h1>Nuovo Modello</h1>

<%= render 'form' %>

<%= link_to 'Torna a elenco modelli', mods_path, :class=>"button large" %>

app/views/mods/show.html.erb
<p id="notice"><%= notice %></p>


  <h3>
  <%= if @mod.shape then @mod.shape.description else "Tipo inesistente" end %> / <%= @mod.description %> </h3>
  



<table>
  <thead>
    <tr>
      <th>Taglie Disponibili</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @sizes.each do |size| %>
      <tr>
        <td><%= size.description %></td>
       
        <td><%= link_to 'Elimina', delete_size_mod_path(:size => size.id), :method => :get %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<table>
  <thead>
    <tr>
      <th>Colori Disponibili</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @colors.each do |color| %>
      <tr>
      <td style="background-color: <%= color.code %>"></td>
        <td><%= color.description %></td>
       
        <td><%= link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'Edit', edit_mod_path(@mod) %> |
<%= link_to 'Back', mods_path %>