config/routes.rb
Rails.application.routes.draw do
  resources :sizes

  get 'static_pages/home'

  get 'static_pages/help'

  resources :artcats

  resources :fonts

  resources :printjobs do
    collection do
      get 'update_shirts'
      get 'update_details'
      get 'mark_completed'
      get 'update_artworks'
      get 'update_art'
    end
  end

  resources :artworks do
    collection do
      get 'catalog'
      get 'update_catalog'
      
      
    end
    member do
      get 'reorder'
    end
  end

  resources :shirts do
    member do
      get :update_size
      get :update_color
  end
  end

  resources :colors

  resources :mods do
    member do
      
      get :delete_size
      
    end
  end

  resources :shapes

  get 'printjobs/new'

  get 'artworks/update_catalog', as: 'update_catalog'

  
  get '/artworks/:id/update_artcat', to: 'artworks#update_artcat', as: 'update_artcat'
  
  get '/artworks/:id/delete_artcat', to: 'artworks#delete_artcat', as: 'delete_artcat'
  
 

  get 'printjobs/new2', as: 'new'

get 'printjobs/update_mods', :as => 'update_mods'
get 'printjobs/update_colors_sizes', :as => 'update_colors_sizes'

root 'static_pages#home'

end

app/models/shape.rb
class Shape < ActiveRecord::Base
	has_many :mod
	has_many :shirt
	has_many :printjob
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  before_action :set_shape, only: [:show, :edit, :update, :destroy]

  # GET /shapes
  # GET /shapes.json
  def index
    @shapes = Shape.all
  end

  # GET /shapes/1
  # GET /shapes/1.json
  def show
  end

  # GET /shapes/new
  def new
    @shape = Shape.new
  end

  # GET /shapes/1/edit
  def edit
  end

  # POST /shapes
  # POST /shapes.json
  def create
    @shape = Shape.new(shape_params)

    respond_to do |format|
      if @shape.save
        format.html { redirect_to @shape, notice: 'Tipo maglia aggiunto.' }
        format.json { render :show, status: :created, location: @shape }
      else
        format.html { render :new }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shapes/1
  # PATCH/PUT /shapes/1.json
  def update
    respond_to do |format|
      if @shape.update(shape_params)
        format.html { redirect_to @shape, notice: 'Tipo maglia modificato.' }
        format.json { render :show, status: :ok, location: @shape }
      else
        format.html { render :edit }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shapes/1
  # DELETE /shapes/1.json
  def destroy
    @shape.destroy
    respond_to do |format|
      format.html { redirect_to shapes_url, notice: 'Tipo maglia eliminato.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shape
      @shape = Shape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shape_params
      params.require(:shape).permit(:description)
    end
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/views/shapes/_form.html.erb
<%= form_for(@shape) do |f| %>
  <% if @shape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shape.errors.count, "error") %> prohibited this shape from being saved:</h2>

      <ul>
      <% @shape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit "Salva",  :class=>"button large"%>
  </div>
<% end %>

app/views/shapes/edit.html.erb
<h1>Modifica tipo</h1>

<%= render 'form' %>

<%= link_to 'Mostra', @shape, :class=>"button large" %> 
<%= link_to 'Indietro', shapes_path, :class=>"button large" %>

app/views/shapes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tipi Maglia</h1>

<table>
  <thead>
    <tr>
      <th>Descrizione</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @shapes.each do |shape| %>
      <tr>
        <td><%= shape.description %></td>
        <td><%= link_to 'Modifica', edit_shape_path(shape) %></td>
        <td><%= link_to 'Elimina', shape, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Aggiungi Nuovo', new_shape_path, :class=>"button large" %>  <%= link_to 'Torna al pannello di controllo', root_path , :class=>"button large" %>

app/views/shapes/new.html.erb
<h1>Nuovo tipo maglia</h1>

<%= render 'form' %>

<%= link_to 'Torna ai tipi maglia', shapes_path, :class=>"button large" %> 

app/views/shapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descrizione:</strong>
  <%= @shape.description %>
</p>

<%= link_to 'Modifica', edit_shape_path(@shape), :class=>"button large" %> 
<%= link_to 'Torna a Elenco', shapes_path, :class=>"button large" %>