config/routes.rb
Rails.application.routes.draw do
  resources :sizes

  get 'static_pages/home'

  get 'static_pages/help'

  resources :artcats

  resources :fonts

  resources :printjobs do
    collection do
      get 'update_shirts'
      get 'update_details'
      get 'mark_completed'
      get 'update_artworks'
      get 'update_art'
    end
  end

  resources :artworks do
    collection do
      get 'catalog'
      get 'update_catalog'
      
      
    end
    member do
      get 'reorder'
    end
  end

  resources :shirts do
    member do
      get :update_size
      get :update_color
  end
  end

  resources :colors

  resources :mods do
    member do
      
      get :delete_size
      
    end
  end

  resources :shapes

  get 'printjobs/new'

  get 'artworks/update_catalog', as: 'update_catalog'

  
  get '/artworks/:id/update_artcat', to: 'artworks#update_artcat', as: 'update_artcat'
  
  get '/artworks/:id/delete_artcat', to: 'artworks#delete_artcat', as: 'delete_artcat'
  
 

  get 'printjobs/new2', as: 'new'

get 'printjobs/update_mods', :as => 'update_mods'
get 'printjobs/update_colors_sizes', :as => 'update_colors_sizes'

root 'static_pages#home'

end

app/models/color.rb
class Color < ActiveRecord::Base

	has_many :printjob
	has_and_belongs_to_many :mod, join_table: :mods_and_colors
	has_and_belongs_to_many :shirt, join_table: :shirts_and_colors
end

app/controllers/colors_controller.rb
class ColorsController < ApplicationController
  before_action :set_color, only: [:show, :edit, :update, :destroy]

  # GET /colors
  # GET /colors.json
  def index
    @colors = Color.all
  end

  # GET /colors/1
  # GET /colors/1.json
  def show
  end

  # GET /colors/new
  def new
    @color = Color.new
  end

  # GET /colors/1/edit
  def edit
  end

  # POST /colors
  # POST /colors.json
  def create
    @color = Color.new(color_params)

    respond_to do |format|
      if @color.save
        format.html { redirect_to @color, notice: 'Color was successfully created.' }
        format.json { render :show, status: :created, location: @color }
      else
        format.html { render :new }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colors/1
  # PATCH/PUT /colors/1.json
  def update
    respond_to do |format|
      if @color.update(color_params)
        format.html { redirect_to @color, notice: 'Color was successfully updated.' }
        format.json { render :show, status: :ok, location: @color }
      else
        format.html { render :edit }
        format.json { render json: @color.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colors/1
  # DELETE /colors/1.json
  def destroy
    @color.destroy
    respond_to do |format|
      format.html { redirect_to colors_url, notice: 'Color was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_color
      @color = Color.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def color_params
      params.require(:color).permit(:description, :code)
    end
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/views/colors/_color.html.erb
<div style="width: 100px; height:100px; display:block; background-color:<%= @colors.first.code %>"></div>

app/views/colors/_form.html.erb
<%= form_for(@color) do |f| %>
  <% if @color.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@color.errors.count, "error") %> prohibited this color from being saved:</h2>

      <ul>
      <% @color.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colors/edit.html.erb
<h1>Editing Color</h1>

<%= render 'form' %>

<%= link_to 'Show', @color %> |
<%= link_to 'Back', colors_path %>

app/views/colors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Colors</h1>

<table>
  <thead>
    <tr>
    <th></th>
      <th>Description</th>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @colors.each do |color| %>
      <tr>
      <td style="background-color: <%= color.code %>;"></td>
        <td><%= color.description %></td>
        <td><%= color.code %></td>
        <td><%= link_to 'Show', color %></td>
        <td><%= link_to 'Edit', edit_color_path(color) %></td>
        <td><%= link_to 'Destroy', color, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Color', new_color_path %>

app/views/colors/new.html.erb
<h1>New Color</h1>

<%= render 'form' %>

<%= link_to 'Back', colors_path %>

app/views/colors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @color.description %>
</p>

<p>
  <strong>Code:</strong>
  <%= @color.code %>
</p>

<%= link_to 'Edit', edit_color_path(@color) %> |
<%= link_to 'Back', colors_path %>