config/routes.rb
Rails.application.routes.draw do
  resources :sizes

  get 'static_pages/home'

  get 'static_pages/help'

  resources :artcats

  resources :fonts

  resources :printjobs do
    collection do
      get 'update_shirts'
      get 'update_details'
      get 'mark_completed'
      get 'update_artworks'
      get 'update_art'
    end
  end

  resources :artworks do
    collection do
      get 'catalog'
      get 'update_catalog'
      
      
    end
    member do
      get 'reorder'
    end
  end

  resources :shirts do
    member do
      get :update_size
      get :update_color
  end
  end

  resources :colors

  resources :mods do
    member do
      
      get :delete_size
      
    end
  end

  resources :shapes

  get 'printjobs/new'

  get 'artworks/update_catalog', as: 'update_catalog'

  
  get '/artworks/:id/update_artcat', to: 'artworks#update_artcat', as: 'update_artcat'
  
  get '/artworks/:id/delete_artcat', to: 'artworks#delete_artcat', as: 'delete_artcat'
  
 

  get 'printjobs/new2', as: 'new'

get 'printjobs/update_mods', :as => 'update_mods'
get 'printjobs/update_colors_sizes', :as => 'update_colors_sizes'

root 'static_pages#home'

end

app/models/shirt.rb
class Shirt < ActiveRecord::Base
	belongs_to :shape
	has_many :printjob
	
	has_and_belongs_to_many :color, join_table: :shirts_and_colors
	has_and_belongs_to_many :size, join_table: :shirts_and_sizes

end

app/controllers/shirts_controller.rb
class ShirtsController < ApplicationController
  before_action :set_shirt, only: [:show, :edit, :update, :destroy]

  # GET /shirts
  # GET /shirts.json
  def index
    @shirts = Shirt.all.order("shape_id")
  end

  # GET /shirts/1
  # GET /shirts/1.json
  def show
    @shirt = Shirt.find(params[:id])
    @avail_sizes = Size.all - @shirt.size
    @avail_colors = Color.all - @shirt.color

  end

  # GET /shirts/new
  def new
    @shirt = Shirt.new
  end

  # GET /shirts/1/edit
  def edit
  end

  def update_size

    @size = Size.find(params[:size])
    @shirt = Shirt.find(params[:id])

    if  @shirt.size.include?(@size)
      @shirt.size.delete(@size)
    else
       @shirt.size << (@size)
    end
   

    respond_to do |format|
      
        format.html { redirect_to @shirt, notice: 'Taglie disponibili aggiornate.' }
        format.json { render :show, status: :created, location: @shirt }
      
    end

  end

  def update_color

    @color = Color.find(params[:color])
    @shirt = Shirt.find(params[:id])

    if  @shirt.color.include?(@color)
      @shirt.color.delete(@color)
    else
       @shirt.color << (@color)
    end
    

    respond_to do |format|
      
        format.html { redirect_to @shirt, notice: 'Colori disponibili aggiornati.' }
        format.json { render :show, status: :created, location: @shirt }
      
    end

  end

  # POST /shirts
  # POST /shirts.json
  def create
    @shirt = Shirt.new(shirt_params)

    respond_to do |format|
      if @shirt.save
        format.html { redirect_to shirts_url, notice: 'Modello aggiunto.' }
        format.json { render :show, status: :created, location: @shirt }
      else
        format.html { render :new }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shirts/1
  # PATCH/PUT /shirts/1.json
  def update
    respond_to do |format|
      if @shirt.update(shirt_params)
        format.html { redirect_to @shirt, notice: 'Modello modificato.' }
        format.json { render :show, status: :ok, location: @shirt }
      else
        format.html { render :edit }
        format.json { render json: @shirt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shirts/1
  # DELETE /shirts/1.json
  def destroy
    @shirt.destroy
    respond_to do |format|
      format.html { redirect_to shirts_url, notice: 'Modello eliminato.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shirt
      @shirt = Shirt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shirt_params
      params.require(:shirt).permit(:description, :shape_id, :path)
    end
end

app/helpers/shirts_helper.rb
module ShirtsHelper
end

app/views/shirts/_form.html.erb
<%= form_for(@shirt) do |f| %>
  <% if @shirt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shirt.errors.count, "error") %> prohibited this shirt from being saved:</h2>

      <ul>
      <% @shirt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :descrizione %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br>
    
    <%= f.collection_select :shape_id, Shape.all, :id, :description %>
  </div>
 
  <div class="actions">
    <%= f.submit "Salva", :class=> "button large" %>
  </div>
<% end %>

app/views/shirts/edit.html.erb
<h1>Editing Shirt</h1>

<%= render 'form' %>

<%= link_to 'Show', @shirt %> |
<%= link_to 'Back', shirts_path %>

app/views/shirts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Modelli</h1>

<table>
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Descrizione</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shirts.each do |shirt| %>
      <tr>
        <td><%= shirt.shape.description %></td>
        <td><%= shirt.description %></td>
        
        <td><%= link_to 'Taglia/colore', shirt %></td>
        <td><%= link_to 'Modifica', edit_shirt_path(shirt) %></td>
        <td><%= link_to 'Elimina', shirt, method: :delete, data: { confirm: 'Sei sicuro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Aggiungi', new_shirt_path, :class => "button large" %> <%= link_to 'Torna alla Home', root_path, :class => "button large" %>

app/views/shirts/new.html.erb
<h1>Nuovo modello</h1>

<%= render 'form' %>

<%= link_to 'Torna a elenco modelli', shirts_path, :class => "button large" %>

app/views/shirts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <h3><%= @shirt.shape.description %> /   <%= @shirt.description %> </h3>

</p>

<h5>Taglie disponibili</h5>
<table>
	<thead>
		<tr>
			<th>Descrizione</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		 <% @shirt.size.each do |size| %>
		 <tr>
		 	<td>
		 		<%= size.description %>
		 	</td>
		 	<td>
		 		<%= link_to 'Elimina', update_size_shirt_path(:size => size.id), :method => :get %> 
		 	</td>
		 </tr>
		 <% end %>
	</tbody>
</table>
<h5>Aggiungi taglia:</h5>
 <% @avail_sizes.each do |a_size| %>
 <%= link_to a_size.description, update_size_shirt_path(:size => a_size.id), :method => :get, :class=>"button small" %>
 <% end %>
<hr>
<h5>Colori disponibili</h5>
<table>
	<thead>
		<tr>
			<th></th>
			<th>Descrizione</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		 <% @shirt.color.each do |color| %>
		 <tr>
		 	<td style="background-color: <%= color.code %>;"></td>
		 	<td>
		 		<%= color.description %>
		 	</td>
		 	<td>
		 		<%= link_to 'Elimina', update_color_shirt_path(:color => color.id), :method => :get %> 
		 	</td>
		 </tr>
		 <% end %>
	</tbody>
</table>
<h5>Aggiungi colore:</h5>
 <% @avail_colors.each do |a_color| %>
 <%= link_to a_color.description, update_color_shirt_path(:color => a_color.id), :method => :get, :class=>"button small" %>
 <% end %>

<hr>
<br>
<%= link_to 'Modifica', edit_shirt_path(@shirt), :class => "button large" %> 
<%= link_to 'Torna Elenco Modelli', shirts_path, :class => "button large" %>